name: widgetbook_challenge
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  # Service locator
  get_it: ^7.2.0
  # Bloc for state management
  flutter_bloc: ^8.0.1
  # Value equality
  equatable: ^2.0.3
  # Functional programming thingies
  dartz: ^0.10.1
  darty_commons: ^0.1.8
  injectable: ^1.5.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.2.0
  very_good_analysis: ^2.4.0
  injectable_generator: ^1.5.3
  bloc_test: ^9.0.3
  build_runner:

flutter:
  uses-material-design: true